accelerator: gpu
devices: 1
precision: 16-mixed
max_epochs: 500
log_every_n_steps: 50
progress_log_every_n_steps: 0
enable_progress_bar: true
epoch_summary_log: true
cudnn_benchmark: false
gradient_clip_val: 0.0
accumulate_grad_batches: 1
checkpoint_epochs: 1
